### ISSUE TITLE
ResultPage呢

### ISSUE THREAD

**Issue by huayanYu** [xwjie/PLMCodeTemplate#1]

**Comment by xwjie** [comment]
pageresult和前台具体使用的分页组件有关系的。不同的组件之间字段、结果都有一些小区别。
大约类似下面这种
`
public class PageResult<T> implements Serializable {

	private static final long serialVersionUID = 1L;

	private List<T> rows;

	private int current;

	private int rowCount;

	private long total;
}
`

**Comment by lishuo9527** [comment]
如果用PageResult，service层如何返回对应的数据类型？ @xwjie

**Comment by xwjie** [comment]
@lishuo9527 @huayanYu 参考我另外一个工程的代码。[ElementVueSpringbootCodeTemplate](https://github.com/xwjie/ElementVueSpringbootCodeTemplate)

定不定pageResultBean，主要看前台怎么样使用。主要是前台的分页组件，二边配合使用。如这里的组件就不需要使用pageResultBean。

后台：
	@GetMapping(value = "/list")
	public ResultBean<PageResp<Config>> list(PageReq param) {
		return new ResultBean<>(configService.listPage(param.toPageable()));
	}

前台，param为分页的参数：
    refreshConfig() {
      this.ajax.get("/config/list", param).then(result => {
        if (result.code == 0) {
          this.configs = result.data;
        } else {
          this.error(result.msg);
        }
      });
    }
