### ISSUE TITLE
如何自定义错误返回码呢

### ISSUE THREAD

**Issue by sicklv** [xwjie/PLMCodeTemplate#12]
如何自定义错误返回码呢，有点不明白

**Comment by xwjie** [comment]
前后台约定就好了。
关键要把握度，不能太粗也不能太细。

可以这样考虑：出现频率，是否需要用户处理，出错的操作
如 
校验出错，只是提示用户而已，那么我们都定为一类，返回1
没有权限，除了提示，可能需要链接到申请权限的页面，这样我们定义为一类，返回2
没有登陆，需要调整到登陆页面，定义为一类，返回-1；
