### ISSUE TITLE
请问返回ResultBean的话，视图如何指定

### ISSUE THREAD

**Issue by cky-thinker** [xwjie/PLMCodeTemplate#2]
请问返回ResultBean的话，视图路径该如何指定。
默认是按url判断的话，那视图的路径比较复杂该怎么办？如何解决？
例如访问URL：/{username}/products  get方式   视图路径是/user/product/list.jsp
如果不指定路径，按URL自动判断应该判断不出

**Comment by xwjie** [comment]
这里这是讨论接口，视图的话就直接把数据加进去就好了。现在我们大部分项目已经没有后台的视图了，前后台完全分离，前台使用mvvm框架，后台提供http接口调用。而且这个趋势越来越明显

**Comment by cky-thinker** [comment]
哦哦，多谢大神指教。
如果公司没有使用spa的话，一定要返回视图的话，我需要如何调整才能适应？

**Comment by xwjie** [comment]
返回试图不冲突啊，我这里写的都是接口相关的。
总体思想要正确，我觉都最重要的思想是：

1. 业务代码上不要看到和业务代码无关的参数，要隐藏掉。
2. 异常要分已知异常和未知异常，不能都一样处理
3. 已知异常要区分需要单独处理的异常和统一处理的异常
