### ISSUE TITLE
请问是完整的工程吗？

### ISSUE THREAD

**Issue by LiaoZhuo** [xwjie/PLMCodeTemplate#6]
想导入到eclipse里学习一下，结果好多问题呢。

**Comment by xwjie** [comment]
是完整的工程，你先要安装 Lombok ( https://projectlombok.org )，然后把src里面的commonm目录加到source（右键 build path-> use as source folder）就可以了。

**Comment by LiaoZhuo** [comment]
可以了，非常感谢(￣▽￣)~*
